---
apiVersion: v1
kind: Service
metadata:
  name: mysql-green
  namespace: argo-rollout
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
