apiVersion: v1
kind: Service
metadata:
  name: wordpress-green
  namespace: argo-rollout
spec:
  selector:
    app: wordpress
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
