---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-creds
  namespace: blog-app
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgCj5wNvB4JXl+FjoPmS0obNCr+olCLPWzFka0TNTerWbgJMr/Ja/SFvkVIZnHREU75RhiGTSGjaVz0o2kG4pi+YkQkEF7o9yTPmPBQx74zqAF0zgSDZ5DtK6+jMfKMlE63w8u4W/UaEUSnG7VKvZUs9sKmP5ZnZQLGdkrBLwBDe6qPCWk9/3sxCxx1wbMgTo2JF3bziHlOHcQAk9mowNIGRU9XTJUL5D6Y0JpXil34LfY0q2VPt1X36xSdn3m6ewaCbOFscUcWKv5A4qG4yZoB5Wo/tmP/UFpVzi433iSmWagbx9rTd1ByIshqp4B8xNU2VVW60ZhXuq993jmOhrnLrrW5MAaepykc/P9NckXeKrF9oEQaumO7lJEf7iFNvyj9xaTViDaLlhNq+svhaSVaE8kPtyVhLfpDHU3SYU+HC2+RgsHV2aKN4wwUsyFZdjOXeCO7cAdloYkdjU+Vm1pMJ0kQxzdvEI76JYX8nFZNYyX6hccwbgSb68cqPKKBPpxCbtXw4iF171HN3kSI9obHn32a22aRGv6gdo+hdI5ZUaSkUEBztWg6V185+0oZKDADuu4M28thXPtbGpt+naUgevQ1QMHevv9rrcrxi5ptjppX5J4whySmJznGu6zWnuIaWzk1pME6DZtYXBASfcpO4Ovi4+6SU+Z5PsRe6rHIiijysWFocfyrBpN1Fg7ouKYLSZO0aOg==
    MONGO_INITDB_ROOT_USERNAME: AgCx+RM2EVYJ2Fa9RjZUzynQWOyygvpfR2V2546Rd3Ud3DZTNV6oC3helFnCrmbNg6L2Dyw+bpbYpOP39QqHpxOWHh0s9Pe8TlD46uXvb4eYwKbor+sPSuq1E5uzAKKIHfUYvnEKeXBRTdV8Fj7zosqDnNOszASGz9y0rqZyiOgO87/jDsddK1Ai95DK2S/lXmtKGw4iqZVV5/YKnaQ8p2Oud7MXbpiueJ8wGyDBtRu4AKpG3Eri/Ksujjm2W4FpBY7DuPMuwAje2J5gRXtJ97EEDJP++hZNiT+Kdgrapjgt2cCNaZ3f1dTASu04CRSP4kyOIkm/coC3WwqyyhD0PEQ4UkRdITIAbMxRkMGuAufAS9Nzj6OhRLlCC90mOMxgBk4vmIqYBfVRQujrq/vszQNmQMMW31xABdQWY7Z6S61sUpBj0kvDfCY65Dg+rdw0GcmMCtIo24/NLAQ1+CInNLgp95c7k36mbtML55Pfqch0oN/WI2NCKJMGDebhXaWSx0F6eH/OSsb9BKZq3WOOAE8bQFpSgDuvRhaui5ExS+7MT/zb4BwPna6JHijS8gU3nRJy+hyu+ktulJn6NjPhoV5UW2Y5oT6lBmHqQN+vFFrM7ZtJkiLJLOPeL5aTX54YSDsSeVI1mtSF0JoK56MbLlvU5ICNuqP6LerTF0QdU7w7SZ+dikva+pUtVzB1zgngzbRKzZ1A
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-creds
      namespace: blog-app
