apiVersion: v1
kind: Service
metadata:
  name: mysql-preview
  namespace: argo-rollout
spec:
  selector:
    app: mysql
    version: green
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
