---
apiVersion: v1
kind: Service
metadata:
  name: mysql-green
  namespace: argo-rollout
  labels:
    app: mysql
    version: green
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
