---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-preview
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
    version: green
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
